#!/bin/bash

BLACK=$( xrdb -query | grep ^\*color0:  | cut -f 2)
RED=$(   xrdb -query | grep ^\*color1:  | cut -f 2)
GREEN=$( xrdb -query | grep ^\*color10: | cut -f 2)
YELLOW=$(xrdb -query | grep ^\*color11: | cut -f 2)
WHITE=$( xrdb -query | grep ^\*color15: | cut -f 2)
GREY=$(  xrdb -query | grep ^\*grey:    | cut -f 2)

BATTERY=0
BATTERY_INFO=$(acpi -b | grep -v unavailable)
# | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

if [[ -z $BATTERY_POWER ]]; then
    # if not battery: return (happens for desktops)
    exit
fi

URGENT_VALUE=10
LOW_VALUE=30
HIGH_VALUE=70
ICON=" "
FG_COLOR=$GREY
BG_COLOR=$BLACK
if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
	ICON=" "
	FG_COLOR=$WHITE
	BG_COLOR=$RED
elif [[ "${BATTERY_STATE}" = "Full" ]]; then
	# ICON=" "
	# FG_COLOR=$GREEN
	exit
elif [[ "${BATTERY_POWER}" -le "${LOW_VALUE}" ]]; then
	ICON=" "
elif [[ "${BATTERY_POWER}" -le "${HIGH_VALUE}" ]]; then
	ICON=" "
else
	ICON=" "
fi

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
    FG_COLOR=$YELLOW
    BG_COLOR=$BLACK
fi

echo "${ICON} ${BATTERY_POWER}%"
echo $ICON
echo $FG_COLOR
echo $BG_COLOR

