#!/bin/bash

IP_ADDRESS=$(wget http://ipinfo.io/ip -qO -)
if [[ -z $IP_ADDRESS ]]; then
    exit
fi
IP_LOC=$(geoiplookup $IP_ADDRESS | grep -oP -m 1 "(?<= )([A-Z]*)(?=,)")
VPN_ICON=""
VPN_ICON=""
VPN_ICON=""

ICON=""

command -v wg > /dev/null # wg exists
if [ $? -eq 0 ]; then
    wg # WG fails if a VPN is enaled, but succeeds if there is nothing to show
    if [ ! $? -eq 0 ]; then
        ICON=$VPN_ICON
    fi
fi

while read line; do
    IFS=' ' read -r -a LINE <<< "$line"
    KNOWN=$(getent hosts ${LINE[0]} | awk '{ print $1 }')
    if [[ $IP_ADDRESS == $KNOWN ]]; then
        IP_LOC=${LINE[1]}
        echo "$ICON  $IP_LOC"
        echo "$IP_LOC"
        exit
    fi
done < ~/.config/vars/known_ips

if [[ "${IP_LOC}" != "" ]]; then
	echo "$ICON  ${IP_LOC}: ${IP_ADDRESS}"
	echo "${IP_LOC}"
fi
