#!/bin/bash

[[ "${BLOCK_BUTTON}" -eq 1 ]] && xdg-open "https://github.com/notifications">/dev/null
N_GH=$(gh api notifications --jq length)
[[ $N_GH != 0 ]] && echo  $N_GH && echo  $N_GH && echo "#FABD2F"
