#!/bin/bash

ICON=
N=$(gh api notifications --jq length)
URL="https://github.com/notifications"

[[ "${BLOCK_BUTTON}" -eq 1 ]] && xdg-open "${URL}">/dev/null
[[ $N != 0 ]] && echo ${ICON} $N && echo ${ICON} $N && echo "#FABD2F"

