#!/bin/bash

YELLOW=$( xrdb -query | grep ^\*color11:  | cut -f 2)
amount=$(mgit status -cdpul ~)
if [ "$amount" -eq "0" ]; then
    exit 0
fi
echo " $amount"
echo " $amount"
echo $YELLOW

exit 0

# Process the "mouse event"
# scroll up
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
	true
# right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	true
# scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
	true
fi

