#!/bin/bash

# 1. Get latest version
LATEST=$(curl -s https://www.optifine.net/downloads | hq -0 '.downloadLine' data | tr '\n' ' ' | sed 's/\x0/\n/g;s/  */ /g'  | sed 's/.*\?f=\(.*.jar\)&.*colDate">\([0-9.]*\).*/\2 \1/' | column -t | head -1)
DATE=$(echo "$LATEST" | cut -d ' ' -f 1)
URL="https://optifine.net/adloadx?f=$(echo "$LATEST" | cut -d ' ' -f 3)"

[[ "${BLOCK_BUTTON}" -eq 1 ]] && xdg-open "${URL}" >/dev/null

# 2. See if latest version is installed
# preview_OptiFine_1.19.3_HD_U_I2_pre4.jar -> 1.19.3-OptiFine_HD_U_I2_pre4
FILENAME=$(echo "$LATEST" | cut -d ' ' -f 3)
QUERY='s/(preview_)*(OptiFine)_([0-9]+.[0-9]+.[0-9])+_(HD_U_[A-Z][0-9])(_pre[0-9]+)*(.jar)/\3-\2_\4\5/'
LASTEST_VERSION_NAME=$(echo "$FILENAME" | sed -r "$QUERY")

ls ~/.minecraft/versions | grep "^$LASTEST_VERSION_NAME$" > /dev/null
if [[ $? != 0 ]];then PRINT=true; else PRINT=false; fi

# 3. Print latest version if not installed
if [[ $PRINT == true ]];then
  YELLOW=$(xrdb -query | grep ^\*color11: | cut -f 2)
  echo $LASTEST_VERSION_NAME
  echo $LASTEST_VERSION_NAME
  echo $YELLOW
fi
