#!/bin/bash

ARGUMENTS="--player spotify"

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	playerctl ${ARGUMENTS} next
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	i3-msg 'workspace 10:    ' > /dev/null
fi

ICON=""

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)

if [[ "${PLAYER_STATUS}" != "Paused" ]] && [[ "${PLAYER_STATUS}" != "Playing" ]]; then
	echo ""
	echo ""
else
	echo "$ICON"
	echo "$ICON"
fi

