#!/bin/bash

ARGUMENTS="--player spotify"

ICON_PLAY=""
ICON_PAUSE=""

RED=$(   xrdb -query | grep ^\*color1:  | cut -f 2)
GREEN=$( xrdb -query | grep ^\*color2:  | cut -f 2)
WHITE=$(   xrdb -query | grep ^\*color15:  | cut -f 2)

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	playerctl ${ARGUMENTS} play-pause
	# pkill -RTMIN+10 i3blocks
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	i3-msg 'workspace 10:    ' > /dev/null
fi

sleep 0.1 #give time for play/pause to go through before getting status

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)

if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
	CUR_ICON="${ICON_PAUSE}"
elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
	CUR_ICON="${ICON_PLAY}"
else
	echo ""
	echo ""
	echo ""
	exit
fi

echo " ${CUR_ICON} "
echo " ${CUR_ICON} "

if [[ "${PLAYER_STATUS}" = "Playing" ]]; then
	echo $GREEN
else
	echo $WHITE
fi

