#!/bin/bash

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
    echo " " "0%"
    echo " " "0%"
    echo "#C55D51"
	exit
fi
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" == 'down' ]]; then
    echo " " "0%"
    echo " " "0%"
    echo "#C55D51"
fi

SSID=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d\: -f2)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# color
if [[ $QUALITY -lt 40 ]]; then
    COLOR="#C55D51"
elif [[ $QUALITY -lt 60 ]]; then
    COLOR="#FE8019"
elif [[ $QUALITY -lt 80 ]]; then
    COLOR="#FABD2F"
else
    COLOR="#B8BB26"
fi

echo " " "$QUALITY% ($SSID)"
echo " "
echo $COLOR

