#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	kek=$(i3-msg 'workspace 11:    ')
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	/usr/share/wicd/daemon/autoconnect.py
fi


if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
	printf '{ "full_text": " 0%%", "label": "", "color": "#C55D51", }\n'
	exit
fi
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" == 'down' ]]; then
	printf '{ "full_text": " 0%%", "label": "", "color": "#C55D51", }\n'
	exit
fi


#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

------------------------------------------------------------------------

# COLORS=("#FF0000" "#FF0000" "#FF1000" "#FF2000" "#FF3000" "#FF4000" "#FF5000" "#FF6000" "#FF7000" "#FF8000" "#FF9000" "#FFA000" "#FFB000" "#FFC000" "#FFD000" "#FFE000" "#FFF000" "#FFFF00" "#F0FF00" "#E0FF00" "#D0FF00" "#C0FF00" "#B0FF00" "#A0FF00" "#90FF00" "#80FF00" "#70FF00" "#60FF00" "#50FF00" "#40FF00" "#30FF00" "#20FF00" "#10FF00" "#00FF00")


# QUALITY=100

# COLOR_IDX=$(echo "$QUALITY/3" | bc)
# COLOR=${COLORS[${COLOR_IDX}]}

# color
if [[ $QUALITY -ge 80 ]]; then
    COLOR="#B8BB26"
elif [[ $QUALITY -lt 40 ]]; then
    COLOR="#C55D51"
elif [[ $QUALITY -lt 60 ]]; then
    COLOR="#FE8019"
elif [[ $QUALITY -lt 80 ]]; then
    COLOR="#FABD2F"
fi

printf '{
	"full_text": " %s%%",
	"label": "",
	"color": "%s",
	}\n' $QUALITY $COLOR
