#!/bin/bash

INTERFACE=$(iw dev | grep Interface | cut -f2 -d " ")

RED=$(   xrdb -query | grep ^\*color1:  | cut -f 2)
GREEN=$( xrdb -query | grep ^\*color10:  | cut -f 2)
YELLOW=$(xrdb -query | grep ^\*color11: | cut -f 2)
GREY=$(  xrdb -query | grep ^\*grey:    | cut -f 2)

if [[ -z $INTERFACE ]]; then #no wifi exists
    exit
fi

if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
    echo " " "0%"
    echo " " "0%"
    echo "$RED"
	exit
fi

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" == 'down' ]]; then
    echo " " "0%"
    echo " " "0%"
    echo "$RED"
fi

SSID=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d\: -f2)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# color
if [[ $QUALITY -lt 50 ]]; then
    COLOR=$YELLOW
else
    COLOR=$GREY
fi

if [[ -z $SSID ]]; then
    echo " "
else
    echo " " "$QUALITY% ($SSID)"
fi

echo " "
echo $COLOR

